### ISSUE TITLE
"Source" button does not work in Chromium

### ISSUE THREAD

**Issue by ceremcem** [paperjs/paperjs.org#32]
As title says, "Source" button in the examples doesn't work. Console shows this error: 

```
"TypeError: Cannot read property 'on' of null
    at createPaperScript (http://paperjs.org/assets/js/scripts.js:435:14)
    at HTMLDivElement.<anonymous> (http://paperjs.org/assets/js/scripts.js:243:3)
    at Function.each (http://paperjs.org/assets/js/jquery.js:4:5347)
    at init.each (http://paperjs.org/assets/js/jquery.js:4:1999)
    at Object.behaviors.paperscript (http://paperjs.org/assets/js/scripts.js:242:28)
    at HTMLDocument.<anonymous> (http://paperjs.org/assets/js/scripts.js:531:15)
    at c (http://paperjs.org/assets/js/jquery.js:4:26051)
    at Object.fireWith [as resolveWith] (http://paperjs.org/assets/js/jquery.js:4:26856)
    at Function.ready (http://paperjs.org/assets/js/jquery.js:4:3305)
    at HTMLDocument.q (http://paperjs.org/assets/js/jquery.js:4:717)"
```

# Version 

Version 69.0.3497.92 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by lehni** [comment]
I am seeing this too. Will investigate it, thanks!

**Comment by ceremcem** [comment]
Nice!
